entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      #middlewares:
        #  - default-headers@file
      tls:
        certResolver: cloudflare
        options: default

api:
  dashboard: true
  insecure: true

log:
  filePath: /logs/traefik.log
  format: json
  level: debug

accesslog:
  filepath: /logs/access.log
  format: json
  bufferingSize: 100

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
  file:
    #directory: /etc/traefik/
    filename: /etc/traefik/treafik.yml
tls:
  certificates:
    - certFile: /ssl/
    - keyFile: /ssl/
http:
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000